# code to print HELLO
print("**    **")
print("**    **")
print("********")
print("**    **")
print("**    **")
print()
print("********")
print("**")
print("********")
print("**")
print("********")
print()
print("**")
print("**")
print("**")
print("**")
print("********")
print()
print("**")
print("**")
print("**")
print("**")
print("********")
print()
print("********")
print("**    **")
print("**    **")
print("**    **")
print("**    **")
print("********")
print()
